---
# tasks file for firefox

# Installation Prerequisites
- name: Delete firefox profiles directory
  file:
    path: "{{ firefox_home }}"
    state: absent

# Install Packages
- name: Ensure firefox dependencies are installed
  apt:
    name: "{{ item }}"
    state: present
  with_items: "{{ firefox_dependencies | list }}"

# - name: Add Firefox repository
#   apt_repository:
#     repo: ppa:mozillateam/firefox-next
#     state: present
#     update_cache: yes
#   register: firefox_add_apt_repo

- name: Ensure firefox packages are installed
  apt:
    name: "{{ item }}"
    state: present
  with_items: "{{ firefox_packages | list }}"

# - name: Install Firefox
#   apt: pkg=firefox state=latest update_cache=yes cache_valid_time={{ aptcachetime }}


# Configure Firefox Profiles
- name: Create firefox profiles
  firefox_profile:
    name: "{{ item.name }}"
    state: present
  # become: no
  become: true
  become_user: "{{ ansible_env.USER }}"
  with_items: "{{ firefox_profiles }}"
  register: firefox_profile_register

# - name: Check that profile exists
#   command: "grep -s 'Name={{ item.name }}' {{ firefox_home }}/profiles.ini"
#   become: true
#   become_user: "{{ ansible_env.USER }}"
#   with_items: "{{ firefox_profiles }}"
#   register: firefox_grep_profile
#   changed_when: false
#   failed_when: firefox_grep_profile.rc > 2

# - name: Ensure firefox profile exists
#   shell: "firefox -no-remote -CreateProfile {{ item.name }} 2>&1"
#   become: true
#   become_user: "{{ ansible_env.USER }}"
#   with_items: "{{ firefox_profiles }}"
#   register: firefox_create_profile
#   changed_when: firefox_grep_profile.rc > 0

# - name: Print out firefox profile
#   debug:
#     msg: "Firefox Profile: {{ firefox_create_profile.stdout | regex_replace(\"Success: created profile '(.+)' at '(.+)'\", \"\\2\") | dirname }}"
#     verbosity: 2

# Install Firefox Global Extensions
- name: Ensure firefox global extension directory exists
  file:
    path: "{{ firefox_addons_dir }}"
    state: directory

- name: Install firefox global extensions
  get_url:
    url: "{{ item.url }}"
    dest: "{{ firefox_addons_dir }}/{{ item.guid }}.xpi"
    mode: 0644
  with_items: "{{ firefox_global_addons }}"
  ignore_errors: true

# Install Firefox Extensions
- name: Install firefox user extensions
  firefox_addon:
    name: "{{ item.1 }}"
    state: present
    profile: "{{ item.0.name }}"
  # become: no
  become: true
  become_user: "{{ ansible_env.USER }}"
  with_subelements:
    - "{{ firefox_profiles }}"
    - extensions

# Set Global Firefox Preferences
- name: Set global firefox preferences
  get_url:
    url: "https://raw.githubusercontent.com/pyllyukko/user.js/5f3a460167fcfb8e4d4152b03c319fd002de8dc0/user.js"
    checksum: "sha256:9344793e14856f51332d9e6e2d8fb9c579da78c5af1a57d09ff62a817d2cc3d5"
    dest: "{{ firefox_global_prefs }}"
    mode: 0644
    backup: yes
    force: yes
  when: firefox_harden

- name: Configure global firefox preferences as default
  replace:
    dest: "{{ firefox_global_prefs }}"
    regexp: 'user_pref\('
    replace: 'pref('
    backup: yes
  when: firefox_harden

# Configure Firefox Preferences
- name: Set firefox user preferences
  template:
    src: user.js.j2
    dest: "{{item.profile_path }}/user.js"
  with_items: "{{ firefox_profile_register.results }}"
  when: firefox_preferences or firefox_profile_preferences[item.profile_name] is defined
  # become: no
  become: true
  become_user: "{{ ansible_env.USER }}"
